name: windows

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1 # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Cache Electron binaries
      uses: actions/cache@v2
      env:
        cache-name: cache-electron-bins
      with:
        # cache location is described here:
        # https://github.com/electron/get#how-it-works
        path: ~/AppData/Local/electron/Cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # - uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    #     architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install
      run: |
        npm install
    - name: npm build
      run: |
        npm run build-windows
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: eDEX-UI.Windows.Installer.exe
        path: dist/*.exe
        if-no-files-found: error

      env:
        CI: true
